apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox

bases:
 - ../base
resources:
- ./namespace.yaml
- ./db.yaml
images:
- name: myproject-laravel-image
  newName: eg.random.ecr.us-east-1.amazonaws.com/myproject-laravel-image
  newTag: 6a1ff2d656e43225d6ab7c281972e4f0cf4935b5
