# Contains generic variables for the application
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_USERNAME: "bn_myapp"
  DB_DATABASE: "bitnami_myapp"